arbcalc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calc.urls')),
]

calc/urls.py
from django.urls import path
from . import views


app_name = "calc"
urlpatterns = [
    path('', views.home, name='home'),
    path('ru', views.home_ru, name='home-ru'),
    path('about', views.about, name='about'),
    path('ru/about', views.about_ru, name='about-ru'),
    path('results', views.result, name='result'),
    path('ru/results', views.result_ru, name='result-ru'),
    path('results/xls', views.to_xlsx, name='xls'),
    path('ru/results/xls', views.to_xlsx_ru, name='xls-ru'),
    path('results/pdf', views.bar_chart, name='pdf'),
    path('ru/results/pdf', views.bar_chart_ru, name='pdf-ru'),
]

calc/models.py
from django.db import models
from django.core.validators import MinValueValidator


class ArbInst(models.Model):
    """ International Arbitral Institutions """
    arb_inst = models.CharField(max_length=64)

    def __str__(self):
        return self.arb_inst


class ArbInstRu(models.Model):
    """ Russian Arbitral Institutions """
    arb_inst = models.CharField(max_length=64)

    def __str__(self):
        return self.arb_inst


class UserRequest(models.Model):
    """ International arbitration - parameters of a dispute """

    ARBS = ((1, '1'), (3, '3'),)
    PARTIES = ((2, '2'), (3, '3'), (4, '4'),)
    PROC = (
        ('Standard', 'Standard'),
        ('Expedited', 'Expedited'),
    )
    EMERGENCY = (
        ('Yes', 'Yes'),
        ('No', 'No'),
    )

    amount = models.FloatField(validators=[MinValueValidator(1)])
    arbs = models.IntegerField(choices=ARBS, default=3)
    proc = models.CharField(max_length=16, choices=PROC, default='Standard')
    ai = models.ManyToManyField(ArbInst)
    ea = models.CharField(max_length=8, choices=EMERGENCY, default='No')
    parties = models.IntegerField(choices=PARTIES, default=2)

    def __str__(self):
        return f'Request N{self.id} for {self.amount}'


class UserRequestRu(models.Model):
    """ Russian domestic arbitration - parameters of a dispute """

    ARBS = ((1, '1'), (3, '3'),)
    TYPE_RU = (
        ('Внутренний', 'Внутренний'),
        ('Корпоративный', 'Корпоративный')
    )
    PROC_RU = (
        ('Стандартная', 'Стандартная'),
        ('Ускоренная', 'Ускоренная'),
    )

    amount = models.FloatField(validators=[MinValueValidator(1)])
    arbs = models.IntegerField(choices=ARBS, default=3)
    ai = models.ManyToManyField(ArbInstRu)
    proc = models.CharField(
        max_length=16, choices=PROC_RU, default='Стандартная')
    type = models.CharField(
        max_length=16, choices=TYPE_RU, default='Внутренний')

    def __str__(self):
        return f'Request N{self.id} for {self.amount}'


class Cost(models.Model):
    """ Results (all fees and comments) calculated based upon dispute parameters
        from a corresponding a UserRequest object. One Cost object per Arbitral
        institution in UserRequest object. A queryset of Cost objects for a
        UserRequest object can be accessed via related name 'costs'
    """

    ai = models.ForeignKey(ArbInst, on_delete=models.CASCADE)
    req = models.ForeignKey(
        UserRequest, on_delete=models.CASCADE, related_name='costs')

    reg_fee = models.FloatField(null=True, blank=True)
    arb_fee = models.FloatField(null=True, blank=True)
    arbs_fee = models.FloatField(null=True, blank=True)
    admin_fee = models.FloatField(null=True, blank=True)
    ea_fee = models.FloatField(null=True, blank=True)

    comment0 = models.TextField(null=True, blank=True)
    comment1 = models.TextField(null=True, blank=True)
    comment2 = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'Request N {self.req.id} ({self.req.amount}) - {self.ai.arb_inst}'


class CostRu(models.Model):
    """ Results (all fees and comments) calculated based upon dispute parameters
        from a corresponding a UserRequestRu object. One CostRu object per Arbitral
        institution in UserRequestRu object. A queryset of CostRu objects for a
        UserRequestRu object can be accessed via related name 'costs'
    """
    ai = models.ForeignKey(ArbInstRu, on_delete=models.CASCADE)
    req = models.ForeignKey(
        UserRequestRu, on_delete=models.CASCADE, related_name='costs')

    reg_fee = models.FloatField(null=True, blank=True)
    arb_fee = models.FloatField(null=True, blank=True)
    arbs_fee = models.FloatField(null=True, blank=True)
    admin_fee = models.FloatField(null=True, blank=True)

    comment0 = models.TextField(null=True, blank=True)
    comment1 = models.TextField(null=True, blank=True)
    comment2 = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'Request N {self.req.id} ({self.req.amount}) - {self.ai.arb_inst}'


class Rate(models.Model):
    """ Exchange rates """
    name = models.CharField(max_length=16)
    rate = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.name

calc/forms.py
from django import forms
from django.forms import ModelForm
from .models import UserRequest, UserRequestRu, ArbInst, ArbInstRu


class RequestForm(forms.ModelForm):
    """ A form with all parameters of a dispute.
        Based on UserRequest Model.
        All fields are required
    """
    def __init__(self, *args, **kwargs):
        super(RequestForm, self).__init__(*args, **kwargs)
        # Change ai field widget from Select to CheckboxSelectMultiple
        self.fields['ai'].widget = forms.CheckboxSelectMultiple(
            choices=self.fields['ai'].choices
        )
        # Change the order of Arbitral institutions
        self.fields['ai'].queryset = ArbInst.objects.order_by('arb_inst')

    class Meta:
        model = UserRequest
        ordering = ['ArbInst__arb_inst']
        labels = {
            "amount": "Ammount in Dispute (USD)",
            "arbs": "Number of Arbitrators",
            "proc": "Type of Procedure",
            "ai": "Arbitral Institution",
            "ea": "Emergency Measures",
            "parties": "Number of Parties",
        }
        fields = ['amount', 'arbs', 'parties', 'proc', 'ea', 'ai']


class RequestFormRu(forms.ModelForm):
    """ A form with all parameters of a dispute.
        Based on UserRequestRu Model.
        All fields are required
    """
    def __init__(self, *args, **kwargs):
        super(RequestFormRu, self).__init__(*args, **kwargs)
        # Change ai field widget from Select to CheckboxSelectMultiple
        self.fields['ai'].widget = forms.CheckboxSelectMultiple(
            choices=self.fields['ai'].choices
        )
        # Change the order of Arbitral institutions
        self.fields['ai'].queryset = ArbInstRu.objects.order_by('arb_inst')

    class Meta:
        model = UserRequestRu
        ordering = ['ArbInst__arb_inst']
        labels = {
            "amount": "Сумма требований",
            "arbs": "Кол-во арбитров",
            "proc": "Вид процедуры",
            "type": "Вид спора",
            "ai": "Арбитражное учреждение",
        }
        fields = ['amount', 'arbs', 'proc', 'type', 'ai']

calc/views.py
# Python libraries
import io
import numpy as np
import matplotlib.pyplot as plt
import xlsxwriter as xw

# Django libraries
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Local imports
from .forms import RequestForm, RequestFormRu
from .models import UserRequest, UserRequestRu
from .utils.arbitration import ai_chooser
from .utils.arbitration_ru import ai_chooser_ru
from .tasks import get_rates


def home(request):
    """ Eng version of Home page with Calculator UI (based on RequestForm).
        If valid data is submitted via POST request UserRequest object is created,
        UserRequest object id is stored in session, corresponding Cost objects
        are created via ai_chooser function call, user is redirected to Results page.
        Otherwise Home page refreshes and error messages are shown (if any)
    """
    if request.method == 'POST':
        form = RequestForm(request.POST)
        if form.is_valid():
            req = form.save()
            request.session['last_id'] = req.pk
            amount = req.amount
            arbs = req.arbs
            proc = req.proc
            parties = req.parties
            measures = req.ea
            ais = req.ai.all()
            ai_chooser(req, ais, amount, arbs, proc, parties, measures)
            return HttpResponseRedirect(reverse('calc:result'))
        else:   # Server-side validation fails
            context = {
                'title': 'Arbitration Fee Calculator',
                'form': form,
            }
            return render(request, 'calc/home.html', context)
    else:
        form = RequestForm()
        context = {
            'form': form,
            'title': 'Arbitration Calculator',
        }
        return render(request, 'calc/home.html', context)


def home_ru(request):
    """ Ru version of Home page with Calculator UI (based on RequestFormRu).
        If valid data is submitted via POST request UserRequestRu object is created,
        UserRequestRu object id is stored in session, corresponding CostRu objects
        are created via ai_chooser_ru function call, user is redirected to Results page.
        Otherwise Home page refreshes and error messages are shown (if any)
    """
    if request.method == 'POST':
        form = RequestFormRu(request.POST)
        if form.is_valid():
            req = form.save()
            request.session['last_id'] = req.pk
            amount = req.amount
            arbs = req.arbs
            proc = req.proc
            type = req.type
            ais = req.ai.all()
            ai_chooser_ru(req, ais, amount, arbs, proc, type)
            return HttpResponseRedirect(reverse('calc:result-ru'))
        else:   # Server-side validation fails
            context = {
                'title': 'Арбитражный калькулятор',
                'form': form,
            }
            return render(request, 'calc/home-ru.html', context)
    else:
        form = RequestFormRu()
        context = {
            'form': form,
            'title': 'Арбитражный калькулятор',
        }
        return render(request, 'calc/home-ru.html', context)


def result(request):
    """ Eng version of the page with results for user's request (UserRequest object).
        If session contains request id (last_id key) all results (Cost objects)
        for corresponding request are displayed.
        Otherwise user is redirected to Home page
    """
    if 'last_id' in request.session:
        last_id = request.session['last_id']
        req = UserRequest.objects.get(pk=last_id)
        amount = req.amount
        arbs = req.arbs
        proc = req.proc
        parties = req.parties
        measures = req.ea
        res = req.costs.all().order_by('arb_fee')
        context = {
            'title': 'Arbitration Fee Calculator - Results',
            'result': res,
            'amount': amount,
            'arbs': arbs,
            'proc': proc,
            'parties': parties,
            'measures': measures,
        }
        return render(request, 'calc/result.html', context)
    else:   # no 'last_id' in session
        return HttpResponseRedirect(reverse('calc:home'))


def result_ru(request):
    """ Ru version of the page with results for user's request (UserRequest object).
        If session contains request id (last_id key) all results (Cost objects)
        for corresponding request are displayed.
        Otherwise user is redirected to Home page
    """
    if 'last_id' in request.session:
        last_id = request.session['last_id']
        req = UserRequestRu.objects.get(pk=last_id)
        amount = req.amount
        arbs = req.arbs
        proc = req.proc
        type = req.type
        res = req.costs.all().order_by('arb_fee')
        context = {
            'title': 'Арбитражный калькулятор - результаты',
            'result': res,
            'amount': amount,
            'arbs': arbs,
            'proc': proc,
            'type': type,
        }
        return render(request, 'calc/result-ru.html', context)
    else:   # no 'last_id' in session
        return HttpResponseRedirect(reverse('calc:home-ru'))


def about(request):
    """ About page """
    context = {'title': 'Arbitration Fee Calculator - About'}
    return render(request, 'calc/about.html', context)


def about_ru(request):
    """ About page (Russian version) """
    context = {'title': 'О калькуляторе'}
    return render(request, 'calc/about-ru.html', context)


def to_xlsx(request):
    """ Creates an xlsx workbook with results in buffer and returns it in
        a HttpResponse object
    """
    # get a request object and corresponding results
    if 'last_id' in request.session:
        last_id = request.session['last_id']
        req = UserRequest.objects.get(pk=last_id)
        res = req.costs.all().order_by('ai__arb_inst')

    # create a workbook and add a worksheet in memory stream
    output = io.BytesIO()
    res_workbook = xw.Workbook(output, {'in_memory': True})
    res_worksheet = res_workbook.add_worksheet(name='Results')

    # cells formatting
    ttl = res_workbook.add_format({
        'bold': True,
        'align': 'center',
        'valign': 'center',
        'bg_color': '#E1E1E1',
        'font_size': 14,
        })
    column_name = res_workbook.add_format({
        'bold': True,
        'bg_color': '#E1E1E1',
        'align': 'center',
        'valign': 'center',
    })
    currency = res_workbook.add_format({'num_format': '#,##0.00'})

    # add title with all parameters
    res_worksheet.merge_range('A1:I1', 'Merged Range')
    title = (
        f'Fees for {req.amount} USD, {req.arbs} Arbitrator(s), {req.parties} '
        f'Parties, {req.proc} Procedure, Emergency Measures: {req.ea}.'
    )
    res_worksheet.write('A1', title, ttl)

    # set columns widths rows hieghts
    res_worksheet.set_column('A:F', 20)
    res_worksheet.set_column('G:I', 40)
    res_worksheet.set_row(0, 30)
    res_worksheet.set_row(1, 30)

    # wrap text
    cell_format = res_workbook.add_format()
    cell_format.set_text_wrap()

    # add column names
    res_worksheet.write('A2', 'Arbitral Institution', column_name)
    res_worksheet.write('B2', 'Arbitration Fee (USD)', column_name)
    res_worksheet.write('C2', 'Arbitrators Fee (USD)', column_name)
    res_worksheet.write('D2', 'Administration Fee (USD)', column_name)
    res_worksheet.write('E2', 'Registration Fee (USD)', column_name)
    res_worksheet.write('F2', 'Emergency Measures (USD)', column_name)
    res_worksheet.write('G2', 'NB', column_name)
    res_worksheet.write('H2', 'Comment 1', column_name)
    res_worksheet.write('I2', 'Comment 2', column_name)

    # add data
    row = 2
    col = 0
    for ai in res:
        res_worksheet.write(row, col, ai.ai.arb_inst)
        res_worksheet.write(row, col+1, ai.arb_fee, currency)
        res_worksheet.write(row, col+2, ai.arbs_fee, currency)
        res_worksheet.write(row, col+3, ai.admin_fee, currency)
        res_worksheet.write(row, col+4, ai.reg_fee, currency)
        if ai.ea_fee:
            res_worksheet.write(row, col+5, ai.ea_fee, currency)
        if ai.comment0:
            res_worksheet.write(row, col+6, ai.comment0, cell_format)
        res_worksheet.write(row, col+7, ai.comment1, cell_format)
        if ai.comment2:
            res_worksheet.write(row, col+8, ai.comment2, cell_format)
        row += 1

    res_workbook.close()

    # creating response
    response = HttpResponse(content_type='application/vnd.ms-excel')

    # telling the browser what the file is named
    response['Content-Disposition'] = "attachment; filename=Results.xlsx"

    # putting the spreadsheet data into the HttpResponse object
    response.write(output.getvalue())

    return response


def to_xlsx_ru(request):
    """ Creates an xlsx workbook with results in buffer and returns it in
        a HttpResponse object
    """
    # get a request object and corresponding results
    if 'last_id' in request.session:
        last_id = request.session['last_id']
        req = UserRequestRu.objects.get(pk=last_id)
        res = req.costs.all().order_by('ai__arb_inst')

    # create a workbook and add a worksheet in memory stream
    output = io.BytesIO()
    res_workbook = xw.Workbook(output, {'in_memory': True})
    res_worksheet = res_workbook.add_worksheet(name='Results')

    # cells formatting
    ttl = res_workbook.add_format({
        'bold': True,
        'align': 'center',
        'valign': 'center',
        'bg_color': '#E1E1E1',
        'font_size': 14,
        })
    column_name = res_workbook.add_format({
        'bold': True,
        'bg_color': '#E1E1E1',
        'align': 'center',
        'valign': 'center',
    })
    currency = res_workbook.add_format({'num_format': '#,##0.00'})

    # add title with all parameters
    res_worksheet.merge_range('A1:H1', 'Merged Range')
    title = (

calc/templates/calc/base-ru.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" charset="utf-8">
    <title> {{ title }} </title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- my css -->
    <link type="text/css" rel="stylesheet" href="{% static 'calc/base.css' %}">
    <style>
      .form-check{
        margin-left: 22px;
      }
      .form-check-label{
        margin-left: 10px;
        position: relative;
        bottom: 3px;
      }
      @media screen and (max-width:500px){
        .form-check-label{
          font-size: large;
        }
        .navbar-custom .navbar-brand,
        .navbar-custom .navbar-text {
          font-size: 22px;
          letter-spacing: 0.5px;
        }
        .navbar-custom .navbar-nav .nav-link {
          font-size: medium;
        }
      }
      @media screen and (max-width:380px){
        .form-check-label{
          font-size: small;
          margin-left: 5px;
          position: relative;
          bottom: 1px;
        }
        .form-check{
          margin-left: 15px;
        }
        .navbar-custom .navbar-brand,
        .navbar-custom .navbar-text {
          font-size: large;
        }
      }
    </style>
  </head>
  <body>
    <div class="flex-wrapper">

      <div>
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom sticky-top">
          <div class="container">
            <a class="navbar-brand" href="{% url 'calc:home-ru' %}">Арбитражный калькулятор</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample07">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'calc:about-ru' %}">О калькуляторе</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'calc:home' %}">Eng</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        {% block content %}{% endblock %}
      </div>

      <div>
        <br>
        <footer class="sticky-bottom my-footer">Последняя проверка изменений в регламенты: 04.12.2020</footer>
      </div>

    </div>

    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

calc/templates/calc/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" charset="utf-8">
    <title> {{ title }} </title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- my css -->
    <link type="text/css" rel="stylesheet" href="{% static 'calc/base.css' %}">
  </head>
  <body>
    <div class="flex-wrapper">

      <div>
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom sticky-top">
          <div class="container">
            <a class="navbar-brand" href="{% url 'calc:home' %}">Arbitration Fee Calculator</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample07">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'calc:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'calc:about' %}">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'calc:home-ru' %}">Ru</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        {% block content %}{% endblock %}
      </div>

      <div>
        <br>
        <footer class="sticky-bottom my-footer">Last check for arbitration rules updates: 04.12.2020</footer>
      </div>

    </div>

    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

calc/templates/calc/result-ru.html
{% extends 'calc/base-ru.html' %}

{% block content %}
<br>
<div class="t_header">
  АРБИТРАЖНЫЕ СБОРЫ
</div>
<div class="t_header2">
    {{ amount }} руб. &#124; {{ arbs }} арбитр(а)
</div>
<div class="t_header2">
    {{ proc }} процедура &#124; {{ type }} спор
</div>
<br>
<div class="cntr">
  <form action="{% url 'calc:xls-ru' %}">
    <input class="bttn" style="margin-left: 12px; margin-right: 0px;" type="submit" value="Скачать xls таблицу" />
  </form>
  <div class="middle-res"></div>
  <form action="{% url 'calc:pdf-ru' %}">
    <input class="bttn" style="margin-left: 0px; margin-right: 12px;" type="submit" value="Скачать диаграмму" />
  </form>
</div>

  <div class="res-wrapper">
    {% for value in result %}
    <div class="resblock">
      <p class="ai">{{ value.ai }}</p>
      {% if value.comment0 %}
        <p class="nb">{{ value.comment0 }}</p>
      {% endif %}

        <p class="arb_fee">{{ value.arb_fee }} руб.</p>
        <div class="a_fee">
          Арбитражный сбор
        </div>
        <table class="equalDivide" width="100%">
            <tr>
              <td rowspan="2">
                <div class="arbs_fee">
                  {{ value.arbs_fee }} руб.
                </div>
                <div class="fee">
                  Гонорарный сбор
                </div>
              </td>
              <td>
                <div class="admin_fee">
                  {{ value.admin_fee }} руб.
                </div>
                <div class="fee">
                  Административный сбор
                </div>
              </td>
            </tr>
            <tr>
              <td>
                <div class="reg_fee">
                  {{ value.reg_fee }} руб.
                </div>
                <div class="fee">
                  Регистрационный сбор
                </div>
              </td>
            </tr>
        </table>

      <hr>
      <p class="com">*{{ value.comment1 }}</p>
      {% if value.comment2 %}
        <p class="com">**{{ value.comment2 }}</p>
      {% endif %}
    </div>
    {% endfor %}

  </div>

<br>
<div class="cntr">
  <form action="{% url 'calc:home-ru' %}">
    <input class="bttn" type="submit" value="Новый рачет" />
  </form>
</div>
<br>



{% endblock %}

calc/templates/calc/result.html
{% extends 'calc/base.html' %}

{% block content %}
<br>
<div class="t_header">
  FEES FOR
</div>
<div class="t_header2">
    {{ amount }} USD &#124; {{ arbs }} Arbitrator(s) &#124; {{ proc }} procedure
</div>
<div class="t_header2">
    {{ parties }} Parties &#124; Emergency Measures: {{ measures }}
</div>
<br>
<div class="cntr">
  <form action="{% url 'calc:xls' %}">
    <input class="bttn" style="margin-left: 12px; margin-right: 0px;" type="submit" value="Download XLS Table" />
  </form>
  <div class="middle-res"></div>
  <form action="{% url 'calc:pdf' %}">
    <input class="bttn" style="margin-left: 0px; margin-right: 12px;" type="submit" value="Download PDF Chart" />
  </form>
</div>

  <div class="res-wrapper">
    {% for value in result %}
    <div class="resblock">
      <p class="ai">{{ value.ai }}</p>
      {% if value.comment0 %}
        <p class="nb">{{ value.comment0 }}</p>
      {% endif %}

        <p class="arb_fee">{{ value.arb_fee }} USD</p>
        <div class="a_fee">
          Arbitration fee
        </div>
        <table class="equalDivide" width="100%">
          {% if value.ea_fee %}
            <tr>
              <td>
                <div class="arbs_fee">
                  {{ value.arbs_fee }} USD
                </div>
                <div class="fee">
                  Arbitrators fee
                </div>
              </td>
              <td>
                <div class="admin_fee">
                  {{ value.admin_fee }} USD
                </div>
                <div class="fee">
                  Administrative fee
                </div>
              </td>
            </tr>
            <tr>
              <td>
                <div class="reg_fee">
                  {{ value.ea_fee }} USD
                </div>
                <div class="fee">
                  Emergency Measures
                </div>
              </td>
              <td>
                <div class="reg_fee">
                  {{ value.reg_fee }} USD
                </div>
                <div class="fee">
                  Registration fee
                </div>
              </td>
            </tr>
          {% else %}
            <tr>
              <td rowspan="2">
                <div class="arbs_fee">
                  {{ value.arbs_fee }} USD
                </div>
                <div class="fee">
                  Arbitrators fee
                </div>
              </td>
              <td>
                <div class="admin_fee">
                  {{ value.admin_fee }} USD
                </div>
                <div class="fee">
                  Administrative fee
                </div>
              </td>
            </tr>
            <tr>
              <td>
                <div class="reg_fee">
                  {{ value.reg_fee }} USD
                </div>
                <div class="fee">
                  Registration fee
                </div>
              </td>
            </tr>
          {% endif %}
        </table>

      <hr>
      <p class="com">*{{ value.comment1 }}</p>
      {% if value.comment2 %}
        <p class="com">**{{ value.comment2 }}</p>
      {% endif %}
    </div>
    {% endfor %}

  </div>

<br>
<div class="cntr">
  <form action="{% url 'calc:home' %}">
    <input class="bttn" type="submit" value="New Request" />
  </form>
</div>
<br>



{% endblock %}